import Head from 'next/head';
import styled from 'styled-components';
import Container from '../components/Container';
export default function Home() {
	return (
		<>
			<Head>
				<title>ItStore - for your wish </title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Main>
				<Container />
			</Main>
		</>
	);
}

const Main = styled.div`
	/* border: 1px solid red; */
`;
